### PR TITLE
Clone for RequestServiceBuilder

### PR DESCRIPTION
**Pull request by kornelski**
Helpful for building a custom `RouterService` (#92)

### CODE REVIEW

**Comment by gsserge** [comment]
@kornelski thanks for the PR! Could you please fix formatting? Also, any particular reason why adding `#[derive(Clone)]` to `RequestServiceBuilder ` wouldn't work?

**Comment by kornelski** [comment]
Formatting looks fine?

I've used custom `Clone, because `derive` would add [incorrect bounds](https://github.com/rust-lang/rust/issues/26925) requiring `B` & `E` to be cloneable for no reason.

**Comment by gsserge** [comment]
> Formatting looks fine?

Take a look at the failed pipeline

```
cargo fmt -- --check
  shell: /usr/bin/bash -e {0}
Diff in /home/runner/work/routerify/routerify/src/service/request_service.rs at line 67:
 
 impl<B, E> Clone for RequestServiceBuilder<B, E> {
     fn clone(&self) -> Self {
-        Self { router: self.router.clone() }
+        Self {
+            router: self.router.clone(),
+        }
     }
 }
```
 
> I've used custom `Clone`, because `derive` would add [incorrect bounds](https://github.com/rust-lang/rust/issues/26925) requiring `B` & `E` to be cloneable for no reason.

Understood 👍

**Comment by gsserge** [comment]
@kornelski I'm about to make another release soon, do you want to get this PR in?

**Comment by kornelski** [comment]
No thanks. I don't like rustfmt.

**Pull request closed without merging**
