### PR TITLE
Configurability for X-POWERED-BY header

### PR DESCRIPTION
**Pull request by Selyatin**
This will allow us to disable the X-POWERED-BY header, it will still be **on** by **default**.

### CODE REVIEW

**Comment by gsserge** [comment]
Thanks for the PR!

Maybe we should just drop this header altogether? This is not the first PR touching it, and in my services I have a special middleware to hide it, which is annoying to be honest. @seanpianka what do you think?

**Comment by seanpianka** [comment]
> ..., and in my services I have a special middleware to hide it

Likewise, I have also disabled the header this way in the past.

I'd be in favor of either removal entirely, or gating this header behind a default-enabled feature flag. Then, we add a short section in the readme on how to disable this header for those interested.

This route avoids adding runtime complexity to router's initialization, maintains the promotion of Routerify, and idiomatically allows for its removal.

**Comment by Selyatin** [comment]
I'm not sure if a default-enabled feature flag is a good option, since if you guys wanna add a new default feature to the crate the developer will have to manually enable those default features just so that he could hide the X-POWERED-BY header, but if you aren't planning on going on a route like that then making it a default-enabled feature is fine in my opinion.

**Comment by gsserge** [comment]
I think that the name `expose()` is a bit too ambiguous. Still, my preference is to completely get rid of this header.

**Comment by gsserge** [comment]
Closing due to https://github.com/routerify/routerify/pull/95

**Pull request closed without merging**
