### PR TITLE
Make the router error type more flexible

### PR DESCRIPTION
**Pull request by gsserge**
While porting a service from Hyper to Routerify I've encountered an issue of not being able to use a simple catch all `Box<dyn std::error::Error + Sync + Send + 'static>` as the handlers' and router error type, in order for the `?` operator to work. My workaround was to use `routerify::Error` as the error type and then `.map_err(|e| ...)?;`  in handlers. 

There are other possible workarounds, and one might reasonably suggest that the proper way would be to crate a custom Error type, possibly an enum, and then implement the `impl From` traits for all possible error, or use `thiserror` crate. However, I still think that being able to get away with just a trait error object or `anyhow::Error` is incredibly important for the convenience. A typical handler performs many things that can fail, from the string-num conversion, to json, to database access and calling third-party services. Being able to return all possible errors with the convenience of the `?` operator and without the need of creating a custom error type is a big deal in my opinion. 

This PR takes its inspiration from Hyper and relaxes the error trait bound to accept the error-like objects, like `Box<dyn Error + Sync + Send>` and `anyhow::Error`, which [do not implement](https://users.rust-lang.org/t/shouldnt-box-t-where-t-error-implement-error-regardless-whether-t-sized/48605) `std::error::Error`. To the best of my knowledge and after testing it with `rouetrify::Error`, `Box<dyn std::error::Error + Sync + Send>`, `anyhow::Error` and `std::io::Error`, this change should not break any existing code.

@rousan I'm aware that you do not have much time for this project anymore, but, as the original designer, could you please take a look at the PR to make sure that these changes are reasonable and do not break any existing code that uses the router. Thanks!

### CODE REVIEW

**Comment by rousan** [comment]
Hi @gsserge, thanks for the PR. I actually did not focus very much on the design of the Error type from the beginning. I should have used `thiserror` or something like that to use `enum pattern`. The PR looks fine, and It can be used as workaround.

Any PR for enum like pattern is always welcome.

**Comment by rousan** [comment]
BTW, @gsserge , Do you want to be an active contributor to this project?

**Comment by gsserge** [comment]
@rousan thanks for such a quick response and for the project in general! It fills a very much needed niche in the Tokio ecosystem by providing a simple yet functional handler layer on top of Hyper.

> BTW, @gsserge , Do you want to be an active contributor to this project? I will send a Github invitation link.

Yes, I've already got a few more things that I'd like to get added. It's also good to see other interested parties contributing to the project!

**Comment by rousan** [comment]
I sent a Github invitation link. You are very welcome to the team.

**Pull request merged**
