### PR TITLE
build: add clippy and fmt to ci

### LINKED ISSUE #85: Run clippy (on CI)
Clippy is great at finding all kinds of issues. Would be nice to run it on CI. If wanted, I can add this.

### PR DESCRIPTION
**Pull request by lucacasonato**
Also fixes various clippy lints.

Closes #85

### CODE REVIEW

**Comment by gsserge** [comment]
Thanks! Could you please use `develop` as the target branch? We are using it for active development. Things get merged into `master` only for a new release.

**Review by gsserge — APPROVED** [review]

**Review by seanpianka — APPROVED** [review]
LGTM!

**Comment by rousan** [comment]
Looks good!

**Comment by lucacasonato** [comment]
> Could you please use develop as the target branch?

Retargeted :-)

**Pull request merged**
