### PR TITLE
Maximum Request Size Feature Proposal

### PR DESCRIPTION
**Pull request by UndefinedBHVR**
This is a proposal for my take on a simple request size limiter. The current system here has a few important notes.
With the big one being that max_size applies to every route specified after it, meaning that it is possible to do things like 
```rust
let router = Router::builder()
  //Routes set below this point have 1KB max request size
  .max_size(1024)
  .get("/a/", route_a)
  .get("/b/", route_b)
  //Routes set below this point have unlimited size
  .max_size(0)
  .get("/c/", route_c)
  .build()
  .unwrap()
```

This also makes it compatible with scopes, with the caveat of scopes not using the max_size of the main route, but this is a limitation of the scope system itself, and would require a completely new system to resolve.

This is not meant to be shipped in 2.0, and is only a proposal, I'd like to see discussion about how we could change and improve this.

### CODE REVIEW

**Comment by UndefinedBHVR** [comment]
I should also note that this feature does not cover transfer-encoding requests. Potentially using the size_hint() function on the Request and rejecting if upper is unbounded or greater than the maximum size requirement could suffice for that situation.

**Comment by gsserge** [comment]
@UndefinedBHVR please include at least some points from our discussion in Discord. At least the fact that with the current scope design we cannot ship this because setting max size on multiple routers won't work.

When I proposed to have something like an RFC I actually meant a discussion about how we can rework scopes, *not* rushing into `max_size` config right away.

**Comment by UndefinedBHVR** [comment]
> @UndefinedBHVR please include at least some points from our discussion in Discord. At least the fact that with the current scope design we cannot ship this because setting max size on multiple routers won't work.
> 
> When I proposed to have something like an RFC I actually meant a discussion about how we can rework scopes, _not_ rushing into `max_size` config right away.

The scope issue you mentioned is not a problem with this system, as shown by the `scoped_max_size()` integration test.

I'd like to completely rework this feature after we introduce a better scoping system. With the current scope system, as you mentioned, scopes are just flattened into the main router, which requires me to do this weirdness here where I'm putting it on the route itself rather than on the router like my initial design. There's not really a performance impact from doing it this way, but its definitely not the most idiomatic.

**Comment by gsserge** [comment]
In the meantime this could be used as a workaround without the need to crate a closure on every request.

```rust
use hyper::{Body, Request, Response, Server, StatusCode};
use routerify::{Middleware, Router, RouterService};

fn size_limit(max_size: u64) -> Middleware<Body, routerify::Error> {
    let f = move |req: Request<Body>| async move {
        if let Some(length) = req.headers().get("Content-Length") {
            let size = length.to_str().unwrap().parse::<u64>().unwrap();
            if size > max_size {
                return Err(routerify::Error::HandlePreMiddlewareRequest(
                    "Above limit".into(),
                ));
            }
        }
        Ok(req)
    };
    Middleware::pre(f)
}

fn router() -> Router<Body, routerify::Error> {
    Router::builder()
        .middleware(size_limit(1))
        .get("/", |_| async { Ok(Response::new(Body::from("hello"))) })
        .err_handler(|err| async move {
            Response::builder()
                .status(StatusCode::BAD_REQUEST)
                .body(Body::from(format!("{:?}", err)))
                .unwrap()
        })
        .build()
        .unwrap()
}

#[tokio::main]
async fn main() {
    let router = router();
    let service = RouterService::new(router).unwrap();
    let addr = ([127, 0, 0, 1], 3000).into();
    Server::bind(&addr).serve(service).await.unwrap();
}
```

In action

```
$ curl -i 127.0.0.1:3000
HTTP/1.1 200 OK
x-powered-by: Routerify v2.0.0-beta-4
content-length: 5
date: Fri, 05 Mar 2021 14:38:15 GMT

hello
~ $ curl -i -d 'Hello!' 127.0.0.1:3000
HTTP/1.1 400 Bad Request
content-length: 69
date: Fri, 05 Mar 2021 14:38:18 GMT

HandlePreMiddlewareRequest(HandlePreMiddlewareRequest("Above limit"))
```

**Comment by UndefinedBHVR** [comment]
I'd say doing it your way would be probably better than what I have here. SInce it would make it function like everything else does, where its applied to a path rather than the routes, and make refactoring it easier later on down if we decide to change the base logic of routerify.

**Comment by seanpianka** [comment]
+1 to creating a middleware to handle this size limiting. 

Take a look at the Routerify organization: there are several drop-in middlewares, e.g. for CORS or query parameters. We could add another one for a pre-built request size limit middleware.

**Comment by UndefinedBHVR** [comment]
> +1 to creating a middleware to handle this size limiting.
> 
> Take a look at the Routerify organization: there are several drop-in middlewares, e.g. for CORS or query parameters. We could add another one for a pre-built request size limit middleware.

Forgot to mention this outside of the Routerify Discord!
The Middleware System appears to not be possible, sadly. Since we'd need to abort the request if the size is exceeded.

**Comment by UndefinedBHVR** [comment]
Will be closing this currently, as mentioned above, this implementation isn't the best way to implement it. I'd also just rather wait for a proper route grouping setup that completely sandboxes the groups or a new error system that would make creating it as a pre-built Middleware possible.

For now, users can easily implement this on their own through a Middleware.

**Pull request closed without merging**
