### PR TITLE
Fix parameter parsing when an extension is used

### LINKED ISSUE #107: Using extension in route params?
Hello,
I'm trying to achieve something like this using routerify:

```rust
Router::builder()
     // ...
    .get("/api/:id.source", get_message_source)
    .get("/api/:id.html", get_message_html)
    .get("/api/:id.eml", get_message_eml)
    .get("/api/:id.plain", get_message_plain)
     // ...
```

By doing so, I'm unable to get the `:id` parameter. The following test can replicate the issue:

```rust
#[tokio::test]
async fn can_extract_extension_path_params() {
    const RESPONSE_TEXT: &str = "Hello world";
    let router: Router<Body, routerify::Error> = Router::builder()
        .get("/api/:id.json", |req| async move {
            let id = req.param("id").unwrap(); // Error here:  "called `Option::unwrap()` on a `None` value'"
            assert_eq!(id, "40");
            let (parts, _) = req.into_parts();
            let id = parts.param("id").unwrap();
            assert_eq!(id, "40");
            Ok(Response::new(RESPONSE_TEXT.into()))
        })
        .build()
        .unwrap();
    let serve = serve(router).await;
    let resp = Client::new()
        .request(
            Request::builder()
                .method("GET")
                .uri(format!("http://{}/api/40.json", serve.addr()))
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    let resp = into_text(resp.into_body()).await;
    assert_eq!(resp, RESPONSE_TEXT.to_owned());
    serve.shutdown();
}
```

Am I doing something wrong, or is it a wider issue?
(I know I can bypass the problem by changing the routes from `/api/:id.source` to `/api/:id/source`, but it'd like to avoid it if possible)
Thanks a lot.

### PR DESCRIPTION
**Pull request by aeyoll**
Fix #107

### CODE REVIEW

**Comment by aeyoll** [comment]
Hello,
Can someone check this PR please? @rousan maybe? Thanks!

**Comment by aeyoll** [comment]
Hello @rousan,
Can you review this PR please?

Thanks a lot

**Comment by rousan** [comment]
@aeyoll, can you please send the PR to develop? We add changes on develop branch and master has the latest stable code. Thanks.

**Comment by aeyoll** [comment]
> @aeyoll, can you please send the PR to develop? We add changes on develop branch and master has the latest stable code. Thanks.

Done!

**Comment by aeyoll** [comment]
Hello @rousan,
I updated the PR last week, can you take a look and merge it please? A new release would also be nice (I need this change to ship a project). Thanks a lot

**Comment by rousan** [comment]
@aeyoll , Released: [v2.2.1](https://github.com/routerify/routerify/releases/tag/v2.2.1).

**Comment by rousan** [comment]
@aeyoll , Released: [v3.0.0](https://github.com/routerify/routerify/releases/tag/v3.0.0)

**Comment by rousan** [comment]
> @aeyoll , Released: [v2.2.1](https://github.com/routerify/routerify/releases/tag/v2.2.1).

Ignore this release. I yanked it from crates.io.

**Comment by aeyoll** [comment]
> > @aeyoll , Released: [v2.2.1](https://github.com/routerify/routerify/releases/tag/v2.2.1).
> 
> Ignore this release. I yanked it from crates.io.

Ok! Can you also make a new release for https://github.com/routerify/routerify-cors/, with `routerify = 3` in the dependencies please?

**Comment by aeyoll** [comment]
> > > @aeyoll , Released: [v2.2.1](https://github.com/routerify/routerify/releases/tag/v2.2.1).
> > 
> > 
> > Ignore this release. I yanked it from crates.io.
> 
> Ok! Can you also make a new release for https://github.com/routerify/routerify-cors/, with `routerify = 3` in the dependencies please?

@rousan I created a new issue for this https://github.com/routerify/routerify-cors/issues/6. Thank!

**Comment by rousan** [comment]
Can you please send a PR for routerify-cors with dependency changes? Thanks.

**Comment by aeyoll** [comment]
> Can you please send a PR for routerify-cors with dependency changes? Thanks.

Hello @rousan! I made the PR: https://github.com/routerify/routerify-cors/pull/7. Thanks a lot

**Pull request merged**
